# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yDOrgorpX5Hii2OOadnoqlMur97Aiqs1
"""

import tensorflow as tf
import numpy as np
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

stat_train = pd.read_csv("mlb-player-stats-Batters.csv") 

stat_train.head()

stat_features = stat_train.copy()
age = stat_features.get('Age')
average = stat_features.get('AVG')

age_array = np.array(age)
avg_array = np.array(average)

stat_model = Sequential()
stat_model.add(Dense(10, input_shape=[1], activation='relu'))
stat_model.add(Dense(1, activation='linear'))

stat_model.compile(loss='mean_squared_error', optimizer='Adam', metrics=['mse'])

stat_model.fit(avg_array, age_array, epochs=10)

stat_model.predict(avg_array[:100])

tf.keras.models.save_model(stat_model, 'saved_model.pbtxt')

converter = tf.lite.TFLiteConverter.from_keras_model(model=stat_model)

tfmodel = converter.convert()

open("playerstats.tflite", "wb").write(tfmodel)